spring.application.name=petRest
server.servlet.context-path=/
server.port=3233


logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.flyway=debug

spring.datasource.url=jdbc:postgresql://localhost:5432/petRestDB
spring.datasource.username=postgres
spring.datasource.password=postQ123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




